version: '3.2'

services:
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        restart: always
        ports:
            - "2181:2181"
    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://206.81.22.187:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_NUM_PARTITIONS: 2

    kafka-manager:
        container_name: kafka-manager
        image: hlebalbau/kafka-manager:stable
        restart: always
        depends_on:
            - kafka
        command: -Dpidfile.path=/dev/null
        environment:
            ZK_HOSTS: "zookeeper:2181"
            APPLICATION_SECRET: "random-secret"
        ports:
            - "9000:90